version: "3.9"

services:
  nastv:
    image: nastv:1.0.0
    container_name: nastv
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
